apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd   # Argo CD's namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/amit2111github/argocd-agent.git'
    targetRevision: main
    path: component

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: express-app

  syncPolicy:
    automated:         # enable auto-sync will make a pull every 3 mins
      prune: true      # by default it dont delete components if not present in repo , prune=true will force it to delete resources which removed from git, 
      selfHeal: true   # overrid manual applied changes eg . kubectl apply -f abc.yaml
    syncOptions:
      - CreateNamespace=true   # create namespace if missing
